# ----
# Site

title: Group Mission Trips Resources
url: "https://resources.groupmissiontrips.com"
baseurl:
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Product documentation template for Jekyll.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Edition Template
  links:

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  workcamp_resources:
    title: Workcamp Resources
    permalink: /workcamps/:path/
    output: true
  woh_resources:
    title: Week of Hope Resources
    permalink: /community-service/:path/
    output: true
  staffing_resources:
    title: Staffing Resources
    permalink: /staffing/:path/
    output: true
    
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "workcamp_resources"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
          format: p h1 h2 h3 h4 h5 h6 pre address div
          bold: true
          italic: true
          link: true
          removeformat: true
          copyformatting: true
          undo: true
          redo: true
          underline: true
          numberedlist: true
          bulletedlist: true
          horizontalrule: true
          code: true
          table: true
          blockquote: true
          image: true
          embed: true
  -
    scope:
      path: ""
      type: "woh_resources"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
          format: p h1 h2 h3 h4 h5 h6 pre address div
          bold: true
          italic: true
          link: true
          removeformat: true
          copyformatting: true
          undo: true
          redo: true
          underline: true
          numberedlist: true
          bulletedlist: true
          horizontalrule: true
          code: true
          table: true
          blockquote: true
          image: true
          embed: true
  -
    scope:
      path: ""
      type: "staffing_resources"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
          format: p h1 h2 h3 h4 h5 h6 pre address div
          bold: true
          italic: true
          link: true
          removeformat: true
          copyformatting: true
          undo: true
          redo: true
          underline: true
          numberedlist: true
          bulletedlist: true
          horizontalrule: true
          code: true
          table: true
          blockquote: true
          image: true
          embed: true
        featured: true
          _inputs:
            featured:
            type: switch
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

  
# -----------
# CloudCannon

types:
  - minor
  - major
